---
# file: tasks/install-nginxlog-exporter.yml
#
# Install Prometheus nginxlog-exporter.
#
# @see http://prometheus.io/docs/introduction/getting_started/
#

- block:

    - name: set internal variables for convenience
      set_fact:
        prometheus_nginxlog_exporter_subdir: "{{ prometheus_install_path }}/nginxlog_exporter-{{ prometheus_nginxlog_exporter_version }}.{{ prometheus_platform_suffix }}"


    - name: set download url for versions >= 0.13.0
      set_fact:
        prometheus_nginxlog_exporter_tarball_url: "https://github.com/alileza/nginxlog_exporter/releases/download/v{{ prometheus_nginxlog_exporter_version }}/nginxlog_exporter-{{ prometheus_nginxlog_exporter_version }}.{{ prometheus_platform_suffix }}.tar.gz"
      when: prometheus_nginxlog_exporter_version | version_compare('0.1.0', '>=')

    - name: set download url for versions < 0.13.0 (OBSOLETE!)
      set_fact:
        prometheus_nginxlog_exporter_tarball_url: "https://github.com/alileza/nginxlog_exporter/releases/download/{{ prometheus_nginxlog_exporter_version }}/nginxlog_exporter-{{ prometheus_nginxlog_exporter_version }}.{{ prometheus_platform_suffix }}.tar.gz"
      when: prometheus_nginxlog_exporter_version | version_compare('0.1.0', '<')

    - name: set daemon dir for versions >= 0.12
      set_fact:
        prometheus_nginxlog_exporter_daemon_dir: "{{ prometheus_nginxlog_exporter_subdir }}"
      # when: prometheus_nginxlog_exporter_version | version_compare('0.0', '>=')


    - name: Check nginxlog_exporter exist
      stat: path={{ prometheus_install_path }}/nginxlog_exporter-{{ prometheus_nginxlog_exporter_version }}.{{ prometheus_platform_suffix }}
      register: nginxlog_exporter_bin

    - name: download and untar nginxlog_exporter tarball
      unarchive:
        src: "{{ prometheus_nginxlog_exporter_tarball_url }}"
        dest: "{{ prometheus_install_path }}"
        copy: no
      when: nginxlog_exporter_bin.stat.exists == False

  when: prometheus_nginxlog_exporter_version != "git"


- block:

    - name: set internal variables for convenience
      set_fact:
        prometheus_nginxlog_exporter_git_url: "https://github.com/prometheus/nginxlog_exporter.git"
        prometheus_nginxlog_exporter_src_path: "{{ prometheus_goroot }}/src/github.com/prometheus/nginxlog_exporter"
        prometheus_nginxlog_exporter_daemon_dir: "{{ prometheus_install_path }}"

    - name: delete the nginxlog_exporter build directory, if necessary
      file: path={{ prometheus_nginxlog_exporter_src_path }}  state=absent
      when: prometheus_rebuild

    - name: mkdir for nginxlog_exporter source code
      file: path={{ prometheus_nginxlog_exporter_src_path }}  state=directory

    - name: clone the nginxlog_exporter project src
      git:
        repo: "{{ prometheus_nginxlog_exporter_git_url }}"
        dest: "{{ prometheus_nginxlog_exporter_src_path }}"
        force: yes

    - name: build nginxlog_exporter source code
      command: make
      args:
        chdir: "{{ prometheus_nginxlog_exporter_src_path }}"
        creates: nginxlog_exporter
      environment:
        GO15VENDOREXPERIMENT: 1
        GOROOT: "{{ prometheus_goroot }}"
        GOPATH: "{{ prometheus_gopath }}"
        PATH: "{{ ansible_env.PATH }}:{{ prometheus_goroot }}/bin:{{ prometheus_gopath }}/bin"

    - name: copy the built nginxlog_exporter to the install path
      command: "cp {{ prometheus_nginxlog_exporter_src_path }}/nginxlog_exporter {{ prometheus_install_path }}"
      args:
        creates: "{{ prometheus_install_path }}/nginxlog_exporter"

  when: prometheus_nginxlog_exporter_version == "git"



- name: set permissions, owner and group
  file: path={{ prometheus_nginxlog_exporter_daemon_dir }}/nginxlog_exporter owner={{ prometheus_user }} group={{ prometheus_group }} mode="go-w"
  when: nginxlog_exporter_bin.stat.exists == False

- name: mkdir for data
  file:
    path: "{{ prometheus_db_path }}"
    state: directory
    owner: "{{ prometheus_user }}"
    group: "{{ prometheus_group }}"
    mode: "u=rwx,g=rx,o="

- name: set nginxlog_exporter variables
  copy: src="../files/etc-default-nginxlog_exporter"  dest=/etc/default/nginxlog_exporter
  register: nginxlog_exporter_config

- debug: var=nginxlog_exporter_config
  notify: reload nginxlog_exporter
  when: nginxlog_exporter_config.changed


- name: copy INIT script to server
  template: src="../templates/nginxlog_exporter.sysvinit.{{ ansible_os_family|lower }}.sh.j2"  dest="/etc/init.d/nginxlog_exporter"  mode="a+x"
  when: not prometheus_nginxlog_exporter_use_systemd|bool

- name: copy systemd config to server
  template: src="../templates/nginxlog_exporter.service.j2"  dest="/lib/systemd/system/nginxlog_exporter.service"
  when: prometheus_nginxlog_exporter_use_systemd|bool

- name: copy config file to server
  template: src="../templates/nginxlog_exporter.config.yml"  dest="/etc/prometheus/nginxlog_exporter.yml"

- name: set INIT status and start
  service: name=nginxlog_exporter enabled=yes state=started
  when: nginxlog_exporter_bin.stat.exists == False
