---
# file: handlers/main.yml
#

- name: restart nginxlog_exporter
  service: name=nginxlog_exporter state=restarted

- name: reload nginxlog_exporter
  service: name=nginxlog_exporter state=reloaded

- name: stop nginxlog_exporter
  service: name=nginxlog_exporter state=stopped
